.TH gnome-subtitles "1" "April 2007"

.SH NAME
Gnome Subtitles \- video subtitling for the GNOME desktop

.SH SYNOPSIS
.B gnome-subtitles
.RI [ options ]
.br

.SH DESCRIPTION
.B Gnome Subtitles
is a subtitle editor for the GNOME desktop. It supports the most
common text-based subtitle formats and allows for subtitle editing, conversion and
synchronization.

.SH OPTIONS
.TP
\fBfilename\fR
Specifies the subtitle file to open when
.B Gnome Subtitles
starts. If this is not specified, a blank subtitle file will be loaded with the "Unsaved Subtitles" label.

.PP
Gnome Subtitles also obeys all normal GNOME and GTK+ command line options.

.SH BUGS
If you find a bug, please report it at http://bugzilla.gnome.org/enter_bug.cgi?product=gnome-subtitles.

.SH AUTHOR
.B Gnome Subtitles 
was written by Pedro Castro <dev@pedrocastro.org>. This manpage was written
by Pedro Castro and Tiago Bortoletto Vaz <tiago@debian-ba.org>.
