.TH gnome-subtitles "1" "August 22, 2011"

.SH NAME
gnome-subtitles \- video subtitling for the GNOME desktop

.SH SYNOPSIS
.B gnome-subtitles
.RI [ options ]
.br

.SH DESCRIPTION
.B Gnome Subtitles
is a subtitle editor for the GNOME desktop. It supports the most common text-based
subtitle formats, video previewing, timings synchronization and subtitle translation.

.SH OPTIONS
.TP
\fBfilename\fR
Specifies the subtitle file to open when
.B Gnome Subtitles
starts. If this is not specified, a blank subtitle file will be loaded with the "Unsaved Subtitles" label.

.PP
Gnome Subtitles also obeys all normal GNOME and GTK+ command line options.

.SH BUGS
If you find a bug, please report it at https://gitlab.gnome.org/GNOME/gnome-subtitles/-/issues/

.SH AUTHOR
.B Gnome Subtitles 
was written by Pedro Castro <pedro@gnomesubtitles.org>. This manpage was written
by Pedro Castro and Tiago Bortoletto Vaz <tiago@debian-ba.org>.
